### ISSUE TITLE
Reimport custom ontology bug

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-CustomOntology#2]
1. I created a custom ontology with this module,
2. I exported this ontology with omeka S (from downloading text file from the namespace url of the ontology, ie, "https://site/ns/pref"
3. If I imported the exported file inside Omeka S, it will recreate all properties and classes because it will add the prefix once again. I obtained `pref:prefmyProperty` instead of `pref:myProperty`

tested on Omeka S 2.0.2

**Comment by kolydart** [comment]
It seems current version (v.3.0.4) is not compatible with Omeka S v.2
[omeka_version_constraint = "^1.0.0"](https://github.com/Daniel-KM/Omeka-S-module-CustomOntology/blob/master/config/module.ini)
I get an error in my installation: 
> Error: Custom Ontology requires Omeka S ^1.0.0

**Comment by pprw** [comment]
The module is working if you comment this line. I don't think my problem is related to it.

**Comment by Daniel-KM** [comment]
The module is upgraded to Omeka 2.

I don't understand how the issue occurs. In /admin/vocabulary/import, you can only import a new vocabulary with another prefix and another uri. If you remove the vocabulary you imported, you can reimport it.

**Comment by Daniel-KM** [comment]
Je viens de mettre le module sous v3. Est-ce que le problème existe toujours ?

**Comment by itsam** [comment]
This bug is still a thing as of today for Omeka S 4.0.4 and Custom Ontology 3.4.5.1 
So please reopen the issue. 

More specifically. 
1) Create a new Ontology
2) Get turtle (myontology.ttl)
3) Import

Then on newly created vocabulary (admin/vocabulary) **edit** your ontology and select ```ontology.ttl``` (either with updates or as is)

the result is to create a "duplicate" of all classes and properties as described above... smt like ```pref:prefmyProperty``` instead of ```pref:myProperty``` (same goes for classes)

Best
